import {campSession as session,withCampAccess} from '@/lib/camp-http';
import {getDB,ensureBaseItems} from '@/lib/camp-db';
import {menuOptions,statusNames} from '@/lib/camp';
export const dynamic='force-dynamic';
const json=(body:unknown,status=200,cookie?:string)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...(cookie?{'Set-Cookie':cookie}:{})}});
function str(v:unknown,n:number){return typeof v==='string'?v.trim().slice(0,n):'';}
async function getCamp(req:Request){try{const db=getDB();await ensureBaseItems(db);const s=session(req);const [items,votes,mine]=await Promise.all([db.prepare('SELECT id,name,quantity,note,status,position FROM shopping ORDER BY position, updated_at').all(),db.prepare('SELECT choices,adults,note FROM meals').all<{choices:string;adults:number;note:string}>(),db.prepare('SELECT adults,choices,note FROM meals WHERE id = ?').bind(s.id).first<{adults:number;choices:string;note:string}>()]);const summary:Record<string,number>=Object.fromEntries(menuOptions.map(x=>[x,0]));for(const v of votes.results){for(const c of JSON.parse(v.choices))if(c in summary)summary[c]++;}return json({items:items.results,mine:mine?{...mine,choices:JSON.parse(mine.choices)}:null,summary,responses:votes.results.length,portions:votes.results.reduce((total,v)=>total+v.adults,0),notes:votes.results.map(v=>v.note).filter(Boolean)},200,s.cookie);}catch(e){console.error('camp load',e);return json({error:'정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.'},503);}}
async function postCamp(req:Request){try{const content=await req.text();if(content.length>6000)return json({error:'입력 내용이 너무 깁니다.'},400);let b;try{b=JSON.parse(content)}catch{return json({error:'입력 내용을 확인해 주세요.'},400)}if(!b||typeof b!=='object'||Array.isArray(b))return json({error:'입력 내용을 확인해 주세요.'},400);const db=getDB();const now=new Date().toISOString();const s=session(req);
 if(b.action==='meal'){if(!Array.isArray(b.choices))return json({error:'메뉴를 선택해 주세요.'},400);const adults=Number(b.adults);const choices=Array.isArray(b.choices)?[...new Set(b.choices)].filter(x=>typeof x==='string'&&menuOptions.includes(x as string)) as string[]:[];if(!Number.isInteger(adults)||adults<1||adults>20||choices.length===0||choices.length!==(new Set(b.choices||[])).size)return json({error:'식사 인원과 메뉴를 확인해 주세요.'},400);if(choices.includes('고기만으로 충분')&&choices.length>1)return json({error:'고기만 선택하거나 추가 메뉴를 골라 주세요.'},400);await db.prepare('INSERT INTO meals (id,adults,choices,note,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET adults=excluded.adults, choices=excluded.choices,note=excluded.note,updated_at=excluded.updated_at').bind(s.id,adults,JSON.stringify(choices),str(b.note,500),now).run();return json({ok:true},200,s.cookie);}
 if(b.action==='add'){const name=str(b.name,60);if(!name)return json({error:'품목명을 입력해 주세요.'},400);const existing=await db.prepare('SELECT id FROM shopping WHERE name = ?').bind(name).first();if(existing)return json({error:'이미 목록에 있는 품목입니다. 수량이나 메모를 수정해 주세요.'},409);const id=crypto.randomUUID();await db.prepare('INSERT INTO shopping (id,name,quantity,note,status,position,updated_at) VALUES (?,?,?,?,?,?,?)').bind(id,name,str(b.quantity,40),str(b.note,250),'need',100,now).run();return json({ok:true,id},200,s.cookie);}
 if(b.action==='edit'){const id=str(b.id,80),name=str(b.name,60);if(!id||!name||!Object.hasOwn(statusNames,b.status))return json({error:'품목 정보를 확인해 주세요.'},400);const result=await db.prepare('UPDATE shopping SET name=?,quantity=?,note=?,status=?,updated_at=? WHERE id=?').bind(name,str(b.quantity,40),str(b.note,250),b.status,now,id).run();if(!result.meta.changes)return json({error:'품목을 찾을 수 없습니다.'},404);return json({ok:true});}
 if(b.action==='status'){if(!Object.hasOwn(statusNames,b.status))return json({error:'준비 상태를 확인해 주세요.'},400);const result=await db.prepare('UPDATE shopping SET status=?,updated_at=? WHERE id=?').bind(b.status,now,str(b.id,80)).run();if(!result.meta.changes)return json({error:'품목을 찾을 수 없습니다.'},404);return json({ok:true});}
 return json({error:'요청을 확인해 주세요.'},400);
 }catch(e){console.error('camp save',e);return json({error:'저장하지 못했습니다. 입력 내용은 그대로 있으니 다시 시도해 주세요.'},503)}}

export const GET=(req:Request)=>withCampAccess(req,()=>getCamp(req));
export const POST=(req:Request)=>withCampAccess(req,()=>postCamp(req));
export const OPTIONS=(req:Request)=>withCampAccess(req,async()=>new Response(null,{status:204}));
